### ISSUE TITLE
Angular-DynaForm "Plunker for basic HTML" currently not available

### ISSUE THREAD

**Issue by gms1** [gms1/angular-dynaform#12]
see https://github.com/unpkg/unpkg/issues/86

**Comment by gms1** [comment]
and
https://unpkg.com/@angular-dynaform/basic@0.6.0/

**Comment by MartinKolarik** [comment]
I'd recommend using https://cdn.jsdelivr.net/npm/@angular-dynaform/basic@0.6.0/ instead.

**Comment by gms1** [comment]
thanks for the suggestion, but seeing XHR errors now
https://embed.plnkr.co/mekIRtHkE3zCpzWmfewN/

**Comment by gms1** [comment]
package is now in the unpkg cache;  plunkers are working fine now
